/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUbk0ihgYv+I= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUbk0ihgYv+I= >>
// ----------- >>
public class Cantiere extends Proprieta {
    // ----------- << attribute.annotations@AAAAAAGSUbouNBzxPbM= >>
    // ----------- >>
    private int[] rentTable;

    // ----------- << attribute.annotations@AAAAAAGSUbqiZx+3GWs= >>
    // ----------- >>
    private GruppoColore colourGroup;

    // ----------- << attribute.annotations@AAAAAAGSUbqlYCAXFNo= >>
    // ----------- >>
    private int numBuildings;

    // ----------- << attribute.annotations@AAAAAAGSUbqndyB3DLc= >>
    // ----------- >>
    private int buildPrice;

    // ----------- << attribute.annotations@AAAAAAGSUbqpzyDXcMg= >>
    // ----------- >>
    private final int MAX_NUM_UNITS;

    public int[] getRentTable() {
        return rentTable;
    }

    public GruppoColore getColourGroup() {
        return colourGroup;
    }

    public int getNumBuildings() {
        return numBuildings;
    }

    public int getBuildPrice() {
        return buildPrice;
    }

    public final int getMAX_NUM_UNITS() {
        return MAX_NUM_UNITS;
    }

    public void setRentTable(int[] rentTable) {
        this.rentTable = rentTable;
    }

    public void setColourGroup(GruppoColore colourGroup) {
        this.colourGroup = colourGroup;
    }

    public void setNumBuildings(int numBuildings) {
        this.numBuildings = numBuildings;
    }

    public void setBuildPrice(int buildPrice) {
        this.buildPrice = buildPrice;
    }

    /**
    * @param name 
    * @param shortName 
    * @param price 
    * @param mortgageValue 
    * @param rentTable 
    * @param colourGroup 
    * @param buildPrice
    */

    // ----------- << method.annotations@AAAAAAGSUcJjskcwp9M= >>
    // ----------- >>
    public Cantiere(String name, String shortName, int price, int mortgageValue, int rentTable, GruppoColore colourGroup, int buildPrice) {
    // ----------- << method.body@AAAAAAGSUcJjskcwp9M= >>
    // ----------- >>
    }
    /**
    * @param numToBuild
    */

    // ----------- << method.annotations@AAAAAAGSUch4vW7eMgI= >>
    // ----------- >>
    public boolean canBuild(int numToBuild) {
    // ----------- << method.body@AAAAAAGSUch4vW7eMgI= >>
    // ----------- >>
    }
    /**
    * @param numToBuild
    */

    // ----------- << method.annotations@AAAAAAGSUciJ2W909GM= >>
    // ----------- >>
    public void build(int numToBuild) {
    // ----------- << method.body@AAAAAAGSUciJ2W909GM= >>
    // ----------- >>
    }
    /**
    * @param numToDemolish
    */

    // ----------- << method.annotations@AAAAAAGSUciMOW/UY2I= >>
    // ----------- >>
    public boolean canDemolish(int numToDemolish) {
    // ----------- << method.body@AAAAAAGSUciMOW/UY2I= >>
    // ----------- >>
    }
    /**
    * @param numToDemolish
    */

    // ----------- << method.annotations@AAAAAAGSUciOKXA0HDo= >>
    // ----------- >>
    public void demolish(int numToDemolish) {
    // ----------- << method.body@AAAAAAGSUciOKXA0HDo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUciQanCUf04= >>
    // ----------- >>
    public void demolishAll() {
    // ----------- << method.body@AAAAAAGSUciQanCUf04= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUciSh3D0ob4= >>
    // ----------- >>
    public int getNumBuildings() {
    // ----------- << method.body@AAAAAAGSUciSh3D0ob4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdGAPXcQWn4= >>
    // ----------- >>
    public int getBuildingPrice() {
    // ----------- << method.body@AAAAAAGSUdGAPXcQWn4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdGCUndwcHo= >>
    // ----------- >>
    public boolean hasBuildings() {
    // ----------- << method.body@AAAAAAGSUdGCUndwcHo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdGEV3fQaPk= >>
    // ----------- >>
    public int getNumHouses() {
    // ----------- << method.body@AAAAAAGSUdGEV3fQaPk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdGGUHgwHGg= >>
    // ----------- >>
    public int getNumHotels() {
    // ----------- << method.body@AAAAAAGSUdGGUHgwHGg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdLIOnz62a4= >>
    // ----------- >>
    public GruppoColore getColourGroup() {
    // ----------- << method.body@AAAAAAGSUdLIOnz62a4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdLKaX1aFLI= >>
    // ----------- >>
    public int getRent() {
    // ----------- << method.body@AAAAAAGSUdLKaX1aFLI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUdLMOX26HbI= >>
    // ----------- >>
    public String toString() {
    // ----------- << method.body@AAAAAAGSUdLMOX26HbI= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUbk0ihgYv+I= >>
// ----------- >>
}