/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScWYz1jlQF1U= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScWYz1jlQF1U= >>
// ----------- >>
public class Carta {
    // ----------- << attribute.annotations@AAAAAAGScWcfPUTWQtQ= >>
    // ----------- >>
    private int type;

    // ----------- << attribute.annotations@AAAAAAGScWfm/kzVZMo= >>
    // ----------- >>
    private String message;

    // ----------- << attribute.annotations@AAAAAAGScWfrJk3pmow= >>
    // ----------- >>
    private int actionID;

    // ----------- << attribute.annotations@AAAAAAGScWfwDE79jHY= >>
    // ----------- >>
    private int parameter;

    // ----------- << attribute.annotations@AAAAAAGScWf09VARKRw= >>
    // ----------- >>
    private int parameters;

    public int getType() {
        return type;
    }

    public String getMessage() {
        return message;
    }

    public int getActionID() {
        return actionID;
    }

    public int getParameter() {
        return parameter;
    }

    public int getParameters() {
        return parameters;
    }

    public void setType(int type) {
        this.type = type;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public void setActionID(int actionID) {
        this.actionID = actionID;
    }

    public void setParameter(int parameter) {
        this.parameter = parameter;
    }

    public void setParameters(int parameters) {
        this.parameters = parameters;
    }

    // ----------- << method.annotations@AAAAAAGScWjfZVoSoSg= >>
    // ----------- >>
    public Carta() {
    // ----------- << method.body@AAAAAAGScWjfZVoSoSg= >>
    // ----------- >>
    }
    /**
    * @param type 
    * @param message 
    * @param actionID
    */

    // ----------- << method.annotations@AAAAAAGScWjpJ1v4AVA= >>
    // ----------- >>
    public Carta(int type, String message, int actionID) {
    // ----------- << method.body@AAAAAAGScWjpJ1v4AVA= >>
    // ----------- >>
    }
    /**
    * @param type 
    * @param message 
    * @param actionID 
    * @param parameter
    */

    // ----------- << method.annotations@AAAAAAGScWjr7l0Mnwo= >>
    // ----------- >>
    public Carta(int type, String message, int actionID, int parameter) {
    // ----------- << method.body@AAAAAAGScWjr7l0Mnwo= >>
    // ----------- >>
    }
    /**
    * @param type 
    * @param message 
    * @param actionID 
    * @param parameters
    */

    // ----------- << method.annotations@AAAAAAGScWjvgF4gZNs= >>
    // ----------- >>
    public Carta(int type, String message, int actionID, int parameters) {
    // ----------- << method.body@AAAAAAGScWjvgF4gZNs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWs5anP6iJ8= >>
    // ----------- >>
    public int getType() {
    // ----------- << method.body@AAAAAAGScWs5anP6iJ8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWs82HUO+iI= >>
    // ----------- >>
    public int getAction() {
    // ----------- << method.body@AAAAAAGScWs82HUO+iI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWs/wHYi0cE= >>
    // ----------- >>
    public int getDestination() {
    // ----------- << method.body@AAAAAAGScWs/wHYi0cE= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWtCinc2HRo= >>
    // ----------- >>
    public int getNumSpaces() {
    // ----------- << method.body@AAAAAAGScWtCinc2HRo= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWtFWHhKHKU= >>
    // ----------- >>
    public int getAmount() {
    // ----------- << method.body@AAAAAAGScWtFWHhKHKU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWtIFnlelJA= >>
    // ----------- >>
    public int getHouseCost() {
    // ----------- << method.body@AAAAAAGScWtIFnlelJA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWtKkHpy8g4= >>
    // ----------- >>
    public int getHotelCost() {
    // ----------- << method.body@AAAAAAGScWtKkHpy8g4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScWtNNnuGSHs= >>
    // ----------- >>
    public String toString() {
    // ----------- << method.body@AAAAAAGScWtNNnuGSHs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScWYz1jlQF1U= >>
// ----------- >>
}