/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSQzErtpK+J40= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSQzErtpK+J40= >>
// ----------- >>
public abstract class Casella {
    // ----------- << attribute.annotations@AAAAAAGSQzGP8JLvOVc= >>
    // ----------- >>
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
    * @param name
    */

    // ----------- << method.annotations@AAAAAAGSQztQ2ZMkmtw= >>
    // ----------- >>
    public Casella(String name) {
    // ----------- << method.body@AAAAAAGSQztQ2ZMkmtw= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUjRbcYRHI6s= >>
    // ----------- >>
    public String getName() {
    // ----------- << method.body@AAAAAAGSUjRbcYRHI6s= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUjSJ/IT4Pv0= >>
    // ----------- >>
    public String toString() {
    // ----------- << method.body@AAAAAAGSUjSJ/IT4Pv0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSQzErtpK+J40= >>
// ----------- >>
}