/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUYsWicaDhR4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUYsWicaDhR4= >>
// ----------- >>
public class Dadi {
    // ----------- << attribute.annotations@AAAAAAGSUYsudMb1hyg= >>
    // ----------- >>
    private final int NUM_DICE;

    // ----------- << attribute.annotations@AAAAAAGSUY2dG8kYIfg= >>
    // ----------- >>
    private int[] dice;

    public final int getNUM_DICE() {
        return NUM_DICE;
    }

    public int[] getDice() {
        return dice;
    }

    public void setDice(int[] dice) {
        this.dice = dice;
    }

    // ----------- << method.annotations@AAAAAAGSUY+DqMn4CN8= >>
    // ----------- >>
    public void roll() {
    // ----------- << method.body@AAAAAAGSUY+DqMn4CN8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUY+vZcp5p50= >>
    // ----------- >>
    public int getDice() {
    // ----------- << method.body@AAAAAAGSUY+vZcp5p50= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUZBimsqsqjc= >>
    // ----------- >>
    public int getTotal() {
    // ----------- << method.body@AAAAAAGSUZBimsqsqjc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUZBkx8rQl9M= >>
    // ----------- >>
    public boolean isDouble() {
    // ----------- << method.body@AAAAAAGSUZBkx8rQl9M= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUZBmuMr0R1U= >>
    // ----------- >>
    public String toString() {
    // ----------- << method.body@AAAAAAGSUZBmuMr0R1U= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUYsWicaDhR4= >>
// ----------- >>
}