/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUbGlp/MVgZY= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUbGlp/MVgZY= >>
// ----------- >>
public class GruppoColore {
    // ----------- << attribute.annotations@AAAAAAGSUbH0DPO96Pg= >>
    // ----------- >>
    private ArrayList<Cantiere> cantieri;

    // ----------- << attribute.annotations@AAAAAAGSUbK0JvQY90I= >>
    // ----------- >>
    private String name;

    public ArrayList<Cantiere> getCantieri() {
        return cantieri;
    }

    public String getName() {
        return name;
    }

    public void setCantieri(ArrayList<Cantiere> cantieri) {
        this.cantieri = cantieri;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
    * @param name
    */

    // ----------- << method.annotations@AAAAAAGSUbOxi/SOXQ4= >>
    // ----------- >>
    public GruppoColore(String name) {
    // ----------- << method.body@AAAAAAGSUbOxi/SOXQ4= >>
    // ----------- >>
    }
    /**
    * @param cantiere
    */

    // ----------- << method.annotations@AAAAAAGSUbPp5PTTllA= >>
    // ----------- >>
    public void addMember(Cantiere cantiere) {
    // ----------- << method.body@AAAAAAGSUbPp5PTTllA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUbRPZ/UOYKQ= >>
    // ----------- >>
    public ArrayList<Cantiere> getMembers() {
    // ----------- << method.body@AAAAAAGSUbRPZ/UOYKQ= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUbRRnfUylS8= >>
    // ----------- >>
    public String getName() {
    // ----------- << method.body@AAAAAAGSUbRRnfUylS8= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUbRT9fVW1BQ= >>
    // ----------- >>
    public int size() {
    // ----------- << method.body@AAAAAAGSUbRT9fVW1BQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUbGlp/MVgZY= >>
// ----------- >>
}