/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScVkwLoWW1NU= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScVkwLoWW1NU= >>
// ----------- >>
public class Imprevisti extends Casella {
    // ----------- << method.annotations@AAAAAAGScVmdUon59bs= >>
    // ----------- >>
    public Imprevisti() {
    // ----------- << method.body@AAAAAAGScVmdUon59bs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScVkwLoWW1NU= >>
// ----------- >>
}