/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUVyLJpRGgG4= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUVyLJpRGgG4= >>
// ----------- >>
public class Main {
    // ----------- << attribute.annotations@AAAAAAGSUV3I8JRyQG8= >>
    // ----------- >>
    private Monopoly monopoly;

    public Monopoly getMonopoly() {
        return monopoly;
    }

    public void setMonopoly(Monopoly monopoly) {
        this.monopoly = monopoly;
    }

    /**
    * @param args[]
    */

    // ----------- << method.annotations@AAAAAAGSUV9SW5R9KUE= >>
    // ----------- >>
    public static void main(String args[]) {
    // ----------- << method.body@AAAAAAGSUV9SW5R9KUE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUVyLJpRGgG4= >>
// ----------- >>
}