/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.archetype.Monopoly;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUh9d54mffW0= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUh9d54mffW0= >>
// ----------- >>
public class MazzoImprevisti extends Mazzo {
    // ----------- << attribute.annotations@AAAAAAGSUiIX0pPEB68= >>
    // ----------- >>
    private final int IMPREVISTI;

    public final int getIMPREVISTI() {
        return IMPREVISTI;
    }

    // ----------- << method.annotations@AAAAAAGSUiJ0bJSjkk4= >>
    // ----------- >>
    public void mazzoImprevisti() {
    // ----------- << method.body@AAAAAAGSUiJ0bJSjkk4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUh9d54mffW0= >>
// ----------- >>
}