/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUiLMZ5liiLE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUiLMZ5liiLE= >>
// ----------- >>
public class Mazzo {
    // ----------- << attribute.annotations@AAAAAAGSUiL8KJqai7U= >>
    // ----------- >>
    private final int AZIONE_VAI_AVANTI;

    // ----------- << attribute.annotations@AAAAAAGSUiUwS6IuxDE= >>
    // ----------- >>
    private final int AZIONE_VAI_INDIETRO;

    // ----------- << attribute.annotations@AAAAAAGSUiUyw6KOIWE= >>
    // ----------- >>
    private final int AZIONE_MUOVI;

    // ----------- << attribute.annotations@AAAAAAGSUiU1A6LuGtI= >>
    // ----------- >>
    private final int AZIONE_VAI_IN_CARCERE;

    // ----------- << attribute.annotations@AAAAAAGSUiU2tKNOs8s= >>
    // ----------- >>
    private final int AZIONE_ESCI_DAL_CARCERE;

    // ----------- << attribute.annotations@AAAAAAGSUiU4maOu9C8= >>
    // ----------- >>
    private final int AZIONE_PAGA_CASE;

    // ----------- << attribute.annotations@AAAAAAGSUiVJKKZhfzE= >>
    // ----------- >>
    private final int AZIONE_PAGA;

    // ----------- << attribute.annotations@AAAAAAGSUiVLB6bBz50= >>
    // ----------- >>
    private final int AZIONE_RICEVI;

    // ----------- << attribute.annotations@AAAAAAGSUiVMqKchNec= >>
    // ----------- >>
    private final int REGALI;

    // ----------- << attribute.annotations@AAAAAAGSUitlV7WuoH8= >>
    // ----------- >>
    private ArrayList<Carta> cards;

    public final int getAZIONE_VAI_AVANTI() {
        return AZIONE_VAI_AVANTI;
    }

    public final int getAZIONE_VAI_INDIETRO() {
        return AZIONE_VAI_INDIETRO;
    }

    public final int getAZIONE_MUOVI() {
        return AZIONE_MUOVI;
    }

    public final int getAZIONE_VAI_IN_CARCERE() {
        return AZIONE_VAI_IN_CARCERE;
    }

    public final int getAZIONE_ESCI_DAL_CARCERE() {
        return AZIONE_ESCI_DAL_CARCERE;
    }

    public final int getAZIONE_PAGA_CASE() {
        return AZIONE_PAGA_CASE;
    }

    public final int getAZIONE_PAGA() {
        return AZIONE_PAGA;
    }

    public final int getAZIONE_RICEVI() {
        return AZIONE_RICEVI;
    }

    public final int getREGALI() {
        return REGALI;
    }

    public ArrayList<Carta> getCards() {
        return cards;
    }

    public void setCards(ArrayList<Carta> cards) {
        this.cards = cards;
    }

    /**
    * @param card
    */

    // ----------- << method.annotations@AAAAAAGSUi4vw8cG/OU= >>
    // ----------- >>
    public void add(Carta card) {
    // ----------- << method.body@AAAAAAGSUi4vw8cG/OU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUi58cchVn4g= >>
    // ----------- >>
    public void shuffle() {
    // ----------- << method.body@AAAAAAGSUi58cchVn4g= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGSUi5+uMi1Ztc= >>
    // ----------- >>
    public Carta get() {
    // ----------- << method.body@AAAAAAGSUi5+uMi1Ztc= >>
    // ----------- >>
    }
    /**
    * @param card
    */

    // ----------- << method.annotations@AAAAAAGSUi6AR8kVhU0= >>
    // ----------- >>
    public Carta put(Carta card) {
    // ----------- << method.body@AAAAAAGSUi6AR8kVhU0= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUiLMZ5liiLE= >>
// ----------- >>
}