/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUh8pQ4hn918= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUh8pQ4hn918= >>
// ----------- >>
public class MazzoProbabilita extends Mazzo {
    // ----------- << attribute.annotations@AAAAAAGSUh+VV41OKVc= >>
    // ----------- >>
    private final int PROBABILITA;

    public final int getPROBABILITA() {
        return PROBABILITA;
    }

    // ----------- << method.annotations@AAAAAAGSUiHClJAm16M= >>
    // ----------- >>
    public void mazzoProbabilita() {
    // ----------- << method.body@AAAAAAGSUiHClJAm16M= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUh8pQ4hn918= >>
// ----------- >>
}