/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;

public class Player {

    private int id;
    private String name;
    private int wallet;
    private boolean isInJail;
    private int location;
    private boolean passedGo;
    private ArrayList<Proprieta> properties;
    private final int MAX_EXIT_JAIL_ATTEMPTS=3;
    private int numExitJailAttempt;
    private ArrayList<Carta> cards;
    
    public Player(int id, String name, int wallet, boolean isInJail, int location) {
    	this.id=id;
    	this.name=name;
    	this.wallet=wallet;
    	this.isInJail=isInJail;
    	this.location=location;
    }
    
    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public int getWallet() {
        return wallet;
    }
    
    public int getLocation() {
        return location;
    }
    
    public int getNumExitJailAttempt() {
        return numExitJailAttempt;
    }

    public boolean isIsInJail() {
        return isInJail;
    }

    public boolean isPassedGo() {
        return passedGo;
    }

    public ArrayList<Proprieta> getProperties() {
        return properties;
    }

    public final int getMAX_EXIT_JAIL_ATTEMPTS() {
        return MAX_EXIT_JAIL_ATTEMPTS;
    }

    public ArrayList<Carta> getCards() {
        return cards;
    }

    public void setId(int id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setWallet(int wallet) {
        this.wallet = wallet;
    }

    public void setIsInJail(boolean isInJail) {
        this.isInJail = isInJail;
    }

    public void setLocation(int location) {
        this.location = location;
    }

    public void setPassedGo(boolean passedGo) {
        this.passedGo = passedGo;
    }

    public void setProperties(ArrayList<Proprieta> properties) {
        this.properties = properties;
    }

    public void setNumExitJailAttempt(int numExitJailAttempt) {
        this.numExitJailAttempt = numExitJailAttempt;
    }

    public void setCards(ArrayList<Carta> cards) {
        this.cards = cards;
    }

    public void move(int totalDiceValue) {
    }

    public void goToJail(int location) {

    }

    public void freeFromJail() {

    }

    public void exceededExitJailAttempts() {
    }

    public void moveTo(int square) {

    }

    public boolean hasGetOutOfJailCard() {
		return isInJail;

    }

    public Carta getCard() {

    }

    public void doTransaction(int amount) {

    }

    public int getTransaction() {
		return MAX_EXIT_JAIL_ATTEMPTS;

    }


    public void addProperty() {

    }

    public boolean isGroupOwner(Cantiere cantiere) {

    }

    public int getNumStationsOwned() {

    }

    public int getNumUtilitiesOwned() {

    }

}