/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScVivFHMVOz8= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScVivFHMVOz8= >>
// ----------- >>
public class Probabilita extends Casella {
    // ----------- << method.annotations@AAAAAAGScVjq9nulaHs= >>
    // ----------- >>
    public Probabilita() {
    // ----------- << method.body@AAAAAAGScVjq9nulaHs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScVivFHMVOz8= >>
// ----------- >>
}