/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUjTR64xrLZo= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUjTR64xrLZo= >>
// ----------- >>
public class Proprieta extends Casella {
    // ----------- << attribute.annotations@AAAAAAGScRotv2znHL0= >>
    // ----------- >>
    private final float VALORE_DISIPOTECA;

    // ----------- << attribute.annotations@AAAAAAGScR4qYt3X43A= >>
    // ----------- >>
    private boolean isOwned;

    // ----------- << attribute.annotations@AAAAAAGScR4swd7Q/GM= >>
    // ----------- >>
    private int price;

    // ----------- << attribute.annotations@AAAAAAGScR58neHsvlE= >>
    // ----------- >>
    private Player owner;

    // ----------- << attribute.annotations@AAAAAAGScR6AUeLlnd8= >>
    // ----------- >>
    private String shortName;

    // ----------- << attribute.annotations@AAAAAAGScR6FGOPe760= >>
    // ----------- >>
    private boolean mortgaged;

    // ----------- << attribute.annotations@AAAAAAGScR6Hj+TXHDY= >>
    // ----------- >>
    private int mortgageValue;

    public final float getVALORE_DISIPOTECA() {
        return VALORE_DISIPOTECA;
    }

    public boolean isIsOwned() {
        return isOwned;
    }

    public int getPrice() {
        return price;
    }

    public Player getOwner() {
        return owner;
    }

    public String getShortName() {
        return shortName;
    }

    public boolean isMortgaged() {
        return mortgaged;
    }

    public int getMortgageValue() {
        return mortgageValue;
    }

    public void setIsOwned(boolean isOwned) {
        this.isOwned = isOwned;
    }

    public void setPrice(int price) {
        this.price = price;
    }

    public void setOwner(Player owner) {
        this.owner = owner;
    }

    public void setShortName(String shortName) {
        this.shortName = shortName;
    }

    public void setMortgaged(boolean mortgaged) {
        this.mortgaged = mortgaged;
    }

    public void setMortgageValue(int mortgageValue) {
        this.mortgageValue = mortgageValue;
    }

    /**
    * @param name 
    * @param price 
    * @param shortName 
    * @param mortgageValue
    */

    // ----------- << method.annotations@AAAAAAGScTBdYCjULDA= >>
    // ----------- >>
    public Proprieta(String name, int price, String shortName, int mortgageValue) {
    // ----------- << method.body@AAAAAAGScTBdYCjULDA= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSf72vq+Oi4= >>
    // ----------- >>
    public String getShortName() {
    // ----------- << method.body@AAAAAAGScSf72vq+Oi4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgQVPx0ols= >>
    // ----------- >>
    public int getPrice() {
    // ----------- << method.body@AAAAAAGScSgQVPx0ols= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgSk/1tyxs= >>
    // ----------- >>
    public int getRent() {
    // ----------- << method.body@AAAAAAGScSgSk/1tyxs= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgU/f5m8tM= >>
    // ----------- >>
    public Player getOwner() {
    // ----------- << method.body@AAAAAAGScSgU/f5m8tM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgXbP9fvHk= >>
    // ----------- >>
    public boolean isOwned() {
    // ----------- << method.body@AAAAAAGScSgXbP9fvHk= >>
    // ----------- >>
    }
    /**
    * @param player
    */

    // ----------- << method.annotations@AAAAAAGScSgZuwBYEtk= >>
    // ----------- >>
    public void setOwner(Player player) {
    // ----------- << method.body@AAAAAAGScSgZuwBYEtk= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgcMwFRw7Y= >>
    // ----------- >>
    public void releaseOwnership() {
    // ----------- << method.body@AAAAAAGScSgcMwFRw7Y= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgo2wJK6Rg= >>
    // ----------- >>
    public void setMortgaged() {
    // ----------- << method.body@AAAAAAGScSgo2wJK6Rg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgrMgND03w= >>
    // ----------- >>
    public void isMortgaged() {
    // ----------- << method.body@AAAAAAGScSgrMgND03w= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSg1kAcnQ4I= >>
    // ----------- >>
    public void setNotMortgaged() {
    // ----------- << method.body@AAAAAAGScSg1kAcnQ4I= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgtigQ80k4= >>
    // ----------- >>
    public int getMortgagedValue() {
    // ----------- << method.body@AAAAAAGScSgtigQ80k4= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSgwKQU1yg4= >>
    // ----------- >>
    public int getMortgageRedemption() {
    // ----------- << method.body@AAAAAAGScSgwKQU1yg4= >>
    // ----------- >>
    }
    /**
    * @param string
    */

    // ----------- << method.annotations@AAAAAAGScSgycAYuLds= >>
    // ----------- >>
    public boolean equals(String string) {
    // ----------- << method.body@AAAAAAGScSgycAYuLds= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScSg4EAggNcQ= >>
    // ----------- >>
    public String toString() {
    // ----------- << method.body@AAAAAAGScSg4EAggNcQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUjTR64xrLZo= >>
// ----------- >>
}