/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScTlQI8N8gDE= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScTlQI8N8gDE= >>
// ----------- >>
public class Societa extends Proprieta {
    // ----------- << attribute.annotations@AAAAAAGScTnYANJgz6M= >>
    // ----------- >>
    private int[] rentTable;

    // ----------- << attribute.annotations@AAAAAAGScTxizNcMEHY= >>
    // ----------- >>
    private Dadi dice;

    public int[] getRentTable() {
        return rentTable;
    }

    public Dadi getDice() {
        return dice;
    }

    public void setRentTable(int[] rentTable) {
        this.rentTable = rentTable;
    }

    public void setDice(Dadi dice) {
        this.dice = dice;
    }

    /**
    * @param name 
    * @param shortName 
    * @param price 
    * @param mortgageValue 
    * @param rentTable 
    * @param dice
    */

    // ----------- << method.annotations@AAAAAAGScTypWdulkeI= >>
    // ----------- >>
    public Societa(String name, String shortName, int price, int mortgageValue, int rentTable, Dadi dice) {
    // ----------- << method.body@AAAAAAGScTypWdulkeI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScT/VaiE9n8k= >>
    // ----------- >>
    public int getRentMultiplier() {
    // ----------- << method.body@AAAAAAGScT/VaiE9n8k= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScUBmGiPO1J8= >>
    // ----------- >>
    public int getRent() {
    // ----------- << method.body@AAAAAAGScUBmGiPO1J8= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScTlQI8N8gDE= >>
// ----------- >>
}