/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScTLp+HsHmgg= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScTLp+HsHmgg= >>
// ----------- >>
public class Stazione extends Proprieta {
    // ----------- << attribute.annotations@AAAAAAGScTR9LJCQCE8= >>
    // ----------- >>
    private int[] rentTable;

    public int[] getRentTable() {
        return rentTable;
    }

    public void setRentTable(int[] rentTable) {
        this.rentTable = rentTable;
    }

    /**
    * @param name 
    * @param shortName 
    * @param price 
    * @param mortgageValue 
    * @param rentTable
    */

    // ----------- << method.annotations@AAAAAAGScTWt6ahuI20= >>
    // ----------- >>
    public Stazione(String name, String shortName, int price, int mortgageValue, int rentTable) {
    // ----------- << method.body@AAAAAAGScTWt6ahuI20= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScTh8XLTiNUo= >>
    // ----------- >>
    public int getRent() {
    // ----------- << method.body@AAAAAAGScTh8XLTiNUo= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScTLp+HsHmgg= >>
// ----------- >>
}