/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGSUZGhaNJfW20= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGSUZGhaNJfW20= >>
// ----------- >>
public class Tabellone {
    // ----------- << attribute.annotations@AAAAAAGSUZHWvtLX0D4= >>
    // ----------- >>
    private final int NUM_SQUARES;

    // ----------- << attribute.annotations@AAAAAAGSUZQZrtNKSys= >>
    // ----------- >>
    private final int POS_VIA;

    // ----------- << attribute.annotations@AAAAAAGSUZQeNtNu87E= >>
    // ----------- >>
    private final int POS_PRIGIONE;

    // ----------- << attribute.annotations@AAAAAAGSUZQgTtOSN1Q= >>
    // ----------- >>
    private final int POS_VAI_IN_PRIGIONE;

    // ----------- << attribute.annotations@AAAAAAGSUZQptdPa470= >>
    // ----------- >>
    private Casella[] squares;

    // ----------- << attribute.annotations@AAAAAAGSUZQrrNP+Xoo= >>
    // ----------- >>
    private GruppoColore marrone;

    // ----------- << attribute.annotations@AAAAAAGSUZQttdQiDag= >>
    // ----------- >>
    private GruppoColore azzurro;

    // ----------- << attribute.annotations@AAAAAAGSUZQvXNRG52o= >>
    // ----------- >>
    private GruppoColore viola;

    // ----------- << attribute.annotations@AAAAAAGSUZQxXdRqJQk= >>
    // ----------- >>
    private GruppoColore arancio;

    // ----------- << attribute.annotations@AAAAAAGSUZQzFdSOTOs= >>
    // ----------- >>
    private GruppoColore rosso;

    // ----------- << attribute.annotations@AAAAAAGSUZQ1BNSyfIA= >>
    // ----------- >>
    private GruppoColore giallo;

    // ----------- << attribute.annotations@AAAAAAGSUaRcB+H8n4Q= >>
    // ----------- >>
    private GruppoColore verde;

    // ----------- << attribute.annotations@AAAAAAGSUaReMeIg5i4= >>
    // ----------- >>
    private GruppoColore blu;

    public final int getNUM_SQUARES() {
        return NUM_SQUARES;
    }

    public final int getPOS_VIA() {
        return POS_VIA;
    }

    public final int getPOS_PRIGIONE() {
        return POS_PRIGIONE;
    }

    public final int getPOS_VAI_IN_PRIGIONE() {
        return POS_VAI_IN_PRIGIONE;
    }

    public Casella[] getSquares() {
        return squares;
    }

    public GruppoColore getMarrone() {
        return marrone;
    }

    public GruppoColore getAzzurro() {
        return azzurro;
    }

    public GruppoColore getViola() {
        return viola;
    }

    public GruppoColore getArancio() {
        return arancio;
    }

    public GruppoColore getRosso() {
        return rosso;
    }

    public GruppoColore getGiallo() {
        return giallo;
    }

    public GruppoColore getVerde() {
        return verde;
    }

    public GruppoColore getBlu() {
        return blu;
    }

    public void setSquares(Casella[] squares) {
        this.squares = squares;
    }

    public void setMarrone(GruppoColore marrone) {
        this.marrone = marrone;
    }

    public void setAzzurro(GruppoColore azzurro) {
        this.azzurro = azzurro;
    }

    public void setViola(GruppoColore viola) {
        this.viola = viola;
    }

    public void setArancio(GruppoColore arancio) {
        this.arancio = arancio;
    }

    public void setRosso(GruppoColore rosso) {
        this.rosso = rosso;
    }

    public void setGiallo(GruppoColore giallo) {
        this.giallo = giallo;
    }

    public void setVerde(GruppoColore verde) {
        this.verde = verde;
    }

    public void setBlu(GruppoColore blu) {
        this.blu = blu;
    }

    /**
    * @param dice
    */

    // ----------- << method.annotations@AAAAAAGSUaZncOKgDOM= >>
    // ----------- >>
    public Tabellone(Dadi dice) {
    // ----------- << method.body@AAAAAAGSUaZncOKgDOM= >>
    // ----------- >>
    }
    /**
    * @param index
    */

    // ----------- << method.annotations@AAAAAAGSUacD6eeBUzI= >>
    // ----------- >>
    public Casella getSquare(int index) {
    // ----------- << method.body@AAAAAAGSUacD6eeBUzI= >>
    // ----------- >>
    }
    /**
    * @param index
    */

    // ----------- << method.annotations@AAAAAAGSUacFsOelVNQ= >>
    // ----------- >>
    public Proprieta getProperty(int index) {
    // ----------- << method.body@AAAAAAGSUacFsOelVNQ= >>
    // ----------- >>
    }
    /**
    * @param shortName
    */

    // ----------- << method.annotations@AAAAAAGSUacHWufJ2bQ= >>
    // ----------- >>
    public Proprieta getProperty(String shortName) {
    // ----------- << method.body@AAAAAAGSUacHWufJ2bQ= >>
    // ----------- >>
    }
    /**
    * @param index
    */

    // ----------- << method.annotations@AAAAAAGSUacI6eftx7k= >>
    // ----------- >>
    public boolean isProperty(int index) {
    // ----------- << method.body@AAAAAAGSUacI6eftx7k= >>
    // ----------- >>
    }
    /**
    * @param shortName
    */

    // ----------- << method.annotations@AAAAAAGSUacKUOgR154= >>
    // ----------- >>
    public boolean isProperty(String shortName) {
    // ----------- << method.body@AAAAAAGSUacKUOgR154= >>
    // ----------- >>
    }
    /**
    * @param shortName
    */

    // ----------- << method.annotations@AAAAAAGSUacMoeg1HcI= >>
    // ----------- >>
    public boolean isCantiere(String shortName) {
    // ----------- << method.body@AAAAAAGSUacMoeg1HcI= >>
    // ----------- >>
    }
    /**
    * @param shortName
    */

    // ----------- << method.annotations@AAAAAAGSUbDE0u9zRlI= >>
    // ----------- >>
    public boolean isStation(String shortName) {
    // ----------- << method.body@AAAAAAGSUbDE0u9zRlI= >>
    // ----------- >>
    }
    /**
    * @param shortName
    */

    // ----------- << method.annotations@AAAAAAGSUbDKqe++3aE= >>
    // ----------- >>
    public boolean isUtility(String shortName) {
    // ----------- << method.body@AAAAAAGSUbDKqe++3aE= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGSUZGhaNJfW20= >>
// ----------- >>
}