/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScUEkAyn1F+w= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScUEkAyn1F+w= >>
// ----------- >>
public class Tassa extends Casella {
    // ----------- << attribute.annotations@AAAAAAGScUOiXn+TjGw= >>
    // ----------- >>
    private int amount;

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    /**
    * @param name 
    * @param amount
    */

    // ----------- << method.annotations@AAAAAAGScUPjJYNnewg= >>
    // ----------- >>
    public Tassa(String name, int amount) {
    // ----------- << method.body@AAAAAAGScUPjJYNnewg= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAGScVP8nureuAk= >>
    // ----------- >>
    public int getAmount() {
    // ----------- << method.body@AAAAAAGScVP8nureuAk= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScUEkAyn1F+w= >>
// ----------- >>
}