/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package IngSftw.Monopoly;


import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAGScVVR3hhfR98= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAGScVVR3hhfR98= >>
// ----------- >>
public class VaiInPrigione extends Casella {
    // ----------- << method.annotations@AAAAAAGScVePKEJ0Uxs= >>
    // ----------- >>
    public VaiInPrigione() {
    // ----------- << method.body@AAAAAAGScVePKEJ0Uxs= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAGScVVR3hhfR98= >>
// ----------- >>
}