/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;


import java.util.*;
import java.time.*;

public class Player {

    private int id;
    private String name;
    private int wallet;
    private boolean isInJail;
    private boolean tiri;
    private int location;
    private boolean passedGo;
    private ArrayList<Proprieta> properties;
    private final int MAX_EXIT_JAIL_ATTEMPTS=3;
    private int numExitJailAttempt;
    private ArrayList<Carta> cards;
    Pedina pedina;
    
    public Player(int id, String name, int wallet, boolean isInJail, int location, Pedina pedina) {
    	this.id = id;
    	this.name = name;
    	this.wallet = wallet;
    	this.isInJail = isInJail;
    	this.location = location;
    	this.pedina = pedina;
    }
    
    
    

}