/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package Model;


import java.util.*;
import java.time.*;

public class Player {

    private int id;
    private String name;
    private int wallet;
    private boolean inPrigione;
    private boolean tiri;
    private int location;
    private boolean passatoVia;
    private ArrayList<Proprieta> proprieta;
    private final int TENTATIVI_MASSIMI_PRIGIONE=3;
    private int tentativiUscitaPrigione;
    private ArrayList<Carta> cards;
    
    public Player(String name) {
    	this.name = name;
    }
    
    public Player(int id, String name, int wallet, boolean isInJail, int location) {
    	this.id = id;
    	this.name = name;
    	this.wallet = wallet;
    	this.inPrigione = inPrigione;
    	this.location = location;
    }
    
    public int getWallet() {
    	return wallet;
    }
    
    public void doTransaction(int totale) {
    	this.wallet = wallet + totale;
    }
    
    public int getLocation() {
    	return location;
    }
    
    public void muovi(int spostamento) {
    	this.location = location + spostamento;
    	if (location >= Tabellone.NUM_SQUARES) {
    		location = location - 40;
    		passatoVia = true;
    	}
    	else {
    		passatoVia = false;
    	}
    	if (location < 0) {
    		location = location + 40;
    	}
    }

	public String getName() {
		return name;
	}

	public boolean passaggioVia() {
		return passatoVia;
	}

	public void vaiInPrigione() {
		location = Tabellone.POS_PRIGIONE;
		inPrigione = true;
		tentativiUscitaPrigione = 0;
	}

	public void addCarta(Carta carta) {
		cards.add(carta);
	}

	public int getNumCasePossesso() {
		int numCase = 0;
		for (Proprieta p : proprieta) {
			if (p instanceof Cantiere) {
				numCase = numCase + ((Cantiere) p).getNumCase();
			}
		}
		return numCase;
	}
	
	public int getNumAlberghiPossesso() {
		int numAlberghi = 0;
		for (Proprieta p : proprieta) {
			if (p instanceof Cantiere) {
				numAlberghi = numAlberghi + ((Cantiere) p).getNumCase();
			}
		}
		return numAlberghi;
	}

	public boolean possessoreGruppo(Cantiere cantiere) {
		boolean haTutteProprieta = true;
		GruppoColore gc = cantiere.getGruppoColore();
		for (Cantiere c : gc.getMembri()) { 
			if (!c.posseduta() || (c.posseduta() && c.getPossessore()!=this)) { //controlla che la proprieta non sia posseduta o se è posseduta controlla che il possessore sia diverso dal player
				haTutteProprieta = false;
			}
		}
		return haTutteProprieta;
	}

	public boolean eInPrigione() {
		return inPrigione;
	}

	public void liberaDaPrigione() {
		inPrigione = false;
	}

	public void fallitoTentativo() {
		tentativiUscitaPrigione++;
	}

	public boolean tentativiTerminati() {
		boolean c = false;
		if(tentativiUscitaPrigione >= TENTATIVI_MASSIMI_PRIGIONE) {
			c = true;
		}
		return c;
	}
    
    
    

}